### ISSUE TITLE
Widget types

### ISSUE THREAD

**Issue by ghost** [RomanBase/flutter_control#1]
Event architecture.

This is a great project.

Hook up Server side svents. There is a dart like for it.
Typically the server sends a create, update or delete to I dictate what change occurred on a data row. The ID is normally in the message just like a typical database row

**Comment by RomanBase** [comment]
Hi, there is few ways how to achieve this, but you still need to provide server stream to App.

You can hook up server stream to **FieldControl<T>** - **field.subscribeTo(stream, converter: (input) => T)** and use **converter** to convert raw data into entity/model/enum etc.
**ActionControl<T>** works as typical observable so can be used that way too.
**ControlFactory** provides global stream to subscribe. You can send events there with given key a type.

If you are familiar with RxDart you can surely use it for this purpose..
