### ISSUE TITLE
Hey there! Superb Package!

### ISSUE THREAD

**Issue by joanofdart** [RomanBase/flutter_control#3]
Hey there RomanBase,

First of all, thank you so much for your dedication and time. This package looks amazing! Please do not take this as a request or anything like that, I'm legit curious if you're planning on releasing a written tutorial about your amazing work? 

Thanks!

**Comment by RomanBase** [comment]
Hi, currently there is no plan for written tutorials from my side.
But I hope someone will do it in near future..
