### ISSUE TITLE
Allow pages to stop from navigating away, e.g. if there are unsaved state changes

### ISSUE THREAD

**Issue by ghost** [RomanBase/flutter_control#4]
Hello,
I am going to start a web project with Flutter, for another project use the Fluro library, however, I could not solve the following problem:
If a user is on a page that contains a form and is making modifications is said form, I would like that if he tries to exit without having saved the modifications (either by putting another url, with the browser's backbutton, ...) it would show him an alertdialog giving him the possibility of canceling the navigation to the new url or, on the contrary, of canceling the modifications and staying on the same page where he is.
The question is, can I do this with flutter_control?
flutter_control has any mechanism by which this functionality can be achieved?
Please, if this functionality is possible with flutter_control could you give me some indications.
Thank you so much for all the help.
Regards,
Jose

**Comment by RomanBase** [comment]
Hey, this is two separate functionality:

1. Back button: Just wrap your Scaffold/Page to  ``WillPopScope`` Widget to handle navigate back action (onWillPop).
2. Url change: Need to be handled in JavaScript (platform-specific code) and via platform channel send events to Dart/Flutter. Also this functionality can vary between different browsers (e.g. Leave Page? dialog in Chrome). Don't know if any library solving this problem, but ``flutter_control`` not, sorry :).

**Comment by jamolina2021** [comment]
Hi @RomanBase
Thank you for the information.
